name: hola

on: [push]

jobs:
    job1:
        name: ubuntu
        runs-on: ubuntu-latest
        steps:
            - name: step1
              uses: actions/checkout@v2
            - name: step2
              run: date +%A%d%B 
    job2:
        name: windows
        runs-on: windows-latest
        steps:
            - name: step1
              uses: actions/checkout@v2
            - name: step2
              run: "Get-Date -DisplayHint Date" 
    job3:
        name: macos
        runs-on: macos-latest
        steps:
            - name: step1
              uses: actions/checkout@v2
            - name: step2
              run: date "+%Y-%m-%d"
    job4:
        name: depends
        steps:
            - name: step1
              uses: actions/checkout@v2
            - name: step2 
              needs: [ubuntu, windows, macos]

        
