name: ARTIFACT
env:
  ARTIFACT_ENVIRONMENT_VARIABLE: custom Artifact environment variable

on: [push]
jobs:
  challenge:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: upload
          uses: actions/upload-artifact@v3.0.0
        - name: download
          uses: actions/download-artifact@v3.0.0
          with: 
            name: ${{ env.ARTIFACT_ENVIRONMENT_VARIABLE }}
            path: .
