name: hola

on: [push]

jobs:
    job1:
        name: first job
        runs-on: ubuntu-latest
        steps:
            - name: step1
              uses: actions/checkout@v2
            - name: step2
              run: date +%A%d%B  
    job2:
        name: second job
        runs-on: windows-latest
        steps:
            - name: step1
              uses: actions/checkout@v2
            - name: step2
              run: "Get-Date -DisplayHint Date" 
    job3:
        name: third job
        runs-on: macos-latest
        steps:
            - name: step1
              uses: actions/checkout@v2
            - name: step2
              run: date "+%Y-%m-%d"
    job4:
        name: fourth job
        runs-on: ubuntu-latest
        needs: [job1, job2, job3]
        steps:
            - name: step1
              uses: actions/checkout@v2
       
      
