name: hola

on: [push]

jobs:
    job1:
        name: ubuntu
        runs-on: ubuntu-latest
        steps:
            - name: step1
              uses: actions/checkout@v2
            - name: step2
              run: date +%A%d%B  
    job2:
        name: windows
        runs-on: windows-latest
        steps:
            - name: step1
              uses: actions/checkout@v2
            - name: step2
              run: "Get-Date -DisplayHint Date" 
    job3:
        name: macos
        runs-on: macos-latest
        steps:
            - name: step1
              uses: actions/checkout@v2
            - name: step2
              run: date "+%Y-%m-%d"
    job4:
<<<<<<< HEAD
        name: fourth job
        runs-on: ubuntu-latest
=======
        name: depends
        runs-on: ubuntu-latest  
>>>>>>> 77e8e88 (third commit)
        needs: [job1, job2, job3]
        steps:
            - name: step1
              uses: actions/checkout@v2
       
      
